# Generated by Django 3.2.7 on 2021-10-14 10:48

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('message', models.CharField(max_length=150)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'CollectionImport')])),
                ('is_viewed', models.BooleanField(default=False)),
                ('params', models.JSONField(default=dict)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
