# Generated by Django 3.2.7 on 2021-10-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleauthentication',
            name='created_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googleauthentication',
            name='updated_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
