# Generated by Django 3.2.7 on 2021-10-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner_id', models.IntegerField()),
                ('private', models.IntegerField(default=1)),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
