# Generated by Django 3.2.7 on 2021-10-04 17:41

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_at',
            field=models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp),
        ),
    ]
