# Generated by Django 3.2.7 on 2021-10-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20211004_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_link',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
