# Generated by Django 3.2.7 on 2021-10-07 07:00

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20211005_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('collection_id', models.IntegerField()),
                ('status', models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'In Queue'), (2, 'In Progress'), (3, 'Completed'), (4, 'Error')])),
                ('file_key', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='image_link',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='collection',
            name='private',
            field=models.IntegerField(default=1),
        ),
    ]
