# Generated by Django 3.2.7 on 2021-10-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20211007_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionimport',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
