# Generated by Django 3.2.7 on 2021-10-16 07:08

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_collectionimport_is_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTextImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('collection_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
