# Generated by Django 3.2.7 on 2021-10-21 16:39

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_delete_collectiontextimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('collection_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
