# Generated by Django 3.2.7 on 2021-10-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20211020_2338'),
        ('collection', '0009_collectiontag_tag'),
    ]

    operations = [
    ]
