# Generated by Django 3.2.7 on 2021-10-24 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20211021_1816'),
        ('collection', '0010_merge_0009_auto_20211020_2338_0009_collectiontag_tag'),
    ]

    operations = [
    ]
