# Generated by Django 3.2.7 on 2021-10-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_merge_20211024_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectiontag',
            name='created_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectiontag',
            name='updated_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='created_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_by',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='origin',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
