# Generated by Django 3.2.7 on 2021-10-04 17:41

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('profile_picture_link', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
