# Generated by Django 3.2.7 on 2021-10-27 09:07

from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211021_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('settings_key', models.CharField(max_length=50)),
                ('settings_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
