# Generated by Django 3.2.7 on 2021-10-05 14:35

import datetime
from django.db import migrations, models
import quiztown.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('updated_at', models.BigIntegerField(default=quiztown.common.models.get_default_current_timestamp)),
                ('name', models.CharField(max_length=30)),
                ('collection_id', models.IntegerField()),
                ('flagged', models.IntegerField(blank=True, default=0)),
                ('image_link', models.CharField(blank=True, default='', max_length=1024)),
                ('next_date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
