# Generated by Django 3.2.7 on 2021-10-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flagged',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'flagged'), (0, 'notflagged')], default=0),
        ),
    ]
