# Generated by Django 3.2.7 on 2021-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_card_flagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='image_link',
            new_name='image_file_key',
        ),
        migrations.AddField(
            model_name='card',
            name='answer_details',
            field=models.JSONField(default={}),
        ),
    ]
