# Generated by Django 3.2.7 on 2021-10-07 09:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20211007_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answer_details',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
