# Generated by Django 3.2.7 on 2021-10-08 18:14

import card.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_answer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_metadata',
            field=models.JSONField(default=dict, encoder=card.models.JSONEncoder),
        ),
        migrations.AlterField(
            model_name='card',
            name='answer_details',
            field=models.JSONField(default=dict, encoder=card.models.JSONEncoder),
        ),
    ]
