# Generated by Django 3.2.7 on 2021-10-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_card_box_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
