# Generated by Django 3.2.7 on 2021-10-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20211014_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flagged',
            field=models.CharField(blank=True, choices=[(1, 'flagged'), (0, 'notflagged')], default=(0, 'image'), max_length=100),
        ),
    ]
