# Generated by Django 3.2.7 on 2021-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='flagged',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'flagged'), (0, 'notflagged')], default=0),
        ),
    ]
