# Generated by Django 3.2.7 on 2021-10-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20211014_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_type',
            new_name='type',
        ),
    ]
