# Generated by Django 3.2.7 on 2021-10-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_name'),
        ('card', '0011_rename_card_type_card_type'),
    ]

    operations = [
    ]
