# Generated by Django 3.2.7 on 2021-10-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_merge_20211017_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collection_import_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
