name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      working-directory: frontend
    - name: tsc
      run: yarn tsc
      working-directory: frontend
    - name: Run ESLint
      run: yarn eslint . --ext .js,.jsx,.ts,.tsx
      working-directory: frontend
